CREATE TABLE current_observation(
uuid varchar not null primary key,
xsinoNamespaceSchemaLocation varchar,
credit varchar,
credit_URL varchar,
suggested_pickup varchar,
suggested_pickup_period varchar,
location varchar,
station_id varchar,
latitude varchar,
longitude varchar,
observation_time varchar,
observation_time_rfc822 varchar,
weather varchar,
temperature_string varchar,
temp_f varchar,
temp_c varchar,
relative_humidity varchar,
wind_varchar varchar,
wind_dir varchar,
wind_degrees varchar,
wind_gust_mph varchar,
wind_mph varchar,
wind_kt varchar,
pressure_varchar varchar,
pressure_mb varchar,
pressure_in varchar,
dewpoint_string varchar,
dewpoint_f varchar,
dewpoint_c varchar,
icon_url_base varchar,
two_day_history_url varchar,
icon_url_name varchar,
ob_url varchar,
disclaimer_url varchar,
copyright_url varchar,
privacy_policy_url varchar);

